name: Build and Push Docker Image
on:
  pull_request:
    types: [labeled]
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
      id: docker_build
      run: |
        IMAGE_NAME=amanvermaclouddrove/dev
        if [ "${{ github.event.pull_request.merged }}" == "true" ]; then
          docker build -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:latest
        elif [ "${{ github.event.label.name }}" == "development" ]; then
          docker build -t $IMAGE_NAME:dev .
          docker push $IMAGE_NAME:dev
#kfjkf
