name: PR Build and Push Docker Image

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build-and-push-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t mukesh18s/hello-world:PR-${{ github.event.number }} .
          docker push mukesh18s/hello-world:PR-${{ github.event.number }}

